DROP TABLE IF EXISTS PRODUCT;
  
CREATE TABLE PRODUCT(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  version INT NOT NULL,
  name VARCHAR(250) NOT NULL,
  productId VARCHAR(250) DEFAULT NULL,
  price DECIMAL(19,2) NOT NULL
);